In [9]:
import twint
import pandas
import nest_asyncio
nest_asyncio.apply()

# Twint Lib
Simple to use, the radius 30km might cover Johor(Malaysia). <br>
Also some tweets dont have Geo tag, so we might miss out a lot of tweets, refer to this <a href="https://medium.com/swlh/how-to-scrape-tweets-by-location-in-python-using-snscrape-8c870fa6ec25">Medium article</a> to read up more <br>
Installation: Might face problem installing using pip, use this code instead: <br>
pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint

In [3]:
#Example
# c = twint.Config()
# c.Search = "covid19"
# #c.Custom_query= "Mental health"
# c.Store_object = True
# c.Lang="en"
# c.Since="2021-01-01"
# c.Until="2021-12-31"
# c.Geo="1.290270,103.851959,30km"
# c.Limit = 3000
# c.Store_csv = True
# c.Output = "S-1.csv"
# twint.run.Search(c)
# type(c)

In [2]:
keyword_list = ['inflation']

In [35]:
# Looping through Keywords list, combine all into a file 
def tweet_twint(date, date2):
    c = twint.Config()
    c.Search = "inflation"
    c.Since = date
    c.Until= date2   # "2021-01-31"
    c.Lang="en"
    c.Filter_retweets = True 
    c.Hide_output = True
    c.Count = True
    c.Pandas = True
    c.Stats = True
    c.Limit = 5800
    twint.run.Search(c)
    df = twint.storage.panda.Tweets_df
    return df

In [36]:
[ "2021-01-15", "2021-02-15", "2021-03-15", "2021-04-15", "2021-05-15"]

x = "2021-01-15"

my_list = []
for i in range(12):
    i+=1
    my_list.append((f'2021-{i}-1', f'2021-{i}-25'))

In [37]:
my_list

[('2021-1-1', '2021-1-25'),
 ('2021-2-1', '2021-2-25'),
 ('2021-3-1', '2021-3-25'),
 ('2021-4-1', '2021-4-25'),
 ('2021-5-1', '2021-5-25'),
 ('2021-6-1', '2021-6-25'),
 ('2021-7-1', '2021-7-25'),
 ('2021-8-1', '2021-8-25'),
 ('2021-9-1', '2021-9-25'),
 ('2021-10-1', '2021-10-25'),
 ('2021-11-1', '2021-11-25'),
 ('2021-12-1', '2021-12-25')]

In [60]:
import time
import pandas as pd
global_df = pd.DataFrame()
for date in my_list:
    df = tweet_twint(date[0], date[1])
    global_df = global_df.append(df)
    time.sleep(4)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 0 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 76 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 0 Tweets.
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 0 Tweets.
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 0 Tweets.
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 77 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 36 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 51 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 15 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 14 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 18 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
[+] Finished: Successfully collected 19 Tweets.

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/4166094802.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  global_df = global_df.append(df)

In [62]:
display(global_df.shape)
global_df.head()

(306, 38)

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1364726749133643776,1364715054743105536,1.614211e+12,2021-02-25 07:59:47,+0800,,@SenJohnThune lmao @ a US senator pretending i...,en,[],[],...,,,,,,"[{'screen_name': 'SenJohnThune', 'name': 'Sena...",,,,
1,1364726726157348872,1364725239482114050,1.614211e+12,2021-02-25 07:59:41,+0800,,@greggnunziata This is not a joking matter for...,en,[],[],...,,,,,,"[{'screen_name': 'greggnunziata', 'name': 'Gre...",,,,
2,1364726593042677762,1364726593042677762,1.614211e+12,2021-02-25 07:59:09,+0800,,Lumber price has gone up over 170% in America ...,en,[],[],...,,,,,,[],,,,
3,1364726591587291136,1364715054743105536,1.614211e+12,2021-02-25 07:59:09,+0800,,@SenJohnThune Always a good sign when Congress...,en,[],[],...,,,,,,"[{'screen_name': 'SenJohnThune', 'name': 'Sena...",,,,
4,1364726552643035140,1364726552643035140,1.614211e+12,2021-02-25 07:59:00,+0800,,BREAKING: Govt plan for exams. 🔹Teachers asse...,en,[],[],...,,,,,,[],,,,

In [63]:
df1 = df1.append(global_df)

/var/folders/4s/qf_5w4sd3_bc6pyrz5jp4hsc0000gn/T/ipykernel_14458/346045598.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(global_df)

In [64]:
df1.shape

(931, 38)

In [72]:
df2 =df1.copy()

In [78]:
#df.loc[df.astype(str).drop_duplicates().index]
df2.iloc[df2.astype(str).drop_duplicates().index]

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1353492222344392707,1353479502261854209,1.611533e+12,2021-01-25 07:57:47,+0800,,@martinkgosi Idk any I’m not bothering with al...,en,[],[],...,,,,,,[],,,,
1,1353492195827965952,1353424796298698753,1.611533e+12,2021-01-25 07:57:40,+0800,,"@neo_hajime Inflation, too much money means pr...",en,[],[],...,,,,,,"[{'screen_name': 'neo_hajime', 'name': 'Hekapo...",,,,
2,1353492090311720960,1353492090311720960,1.611533e+12,2021-01-25 07:57:15,+0800,,Exerts from the Daily Fix - Talk of inflation ...,en,"[fomc, trading]",[usd],...,,,,,,[],,,,
3,1353492059370479617,1353355472032567296,1.611533e+12,2021-01-25 07:57:08,+0800,,@fuzzle7777 @GrumpyDad3 Regards the Michellins...,en,[],[],...,,,,,,"[{'screen_name': 'fuzzle7777', 'name': 'Lummel...",,,,
4,1353492005008113665,1353491523392966659,1.611533e+12,2021-01-25 07:56:55,+0800,,"Oh Mike, since you're clearly unaware of infla...",en,[],[],...,,,,,,[],,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12,1396978462263582720,1396978462263582720,1.621901e+12,2021-05-25 07:56:34,+0800,,Uphold Chairman Powell Thought Serve the Peopl...,en,[],[],...,,,,,,[],,,,
13,1396978398249971717,1396960762250203136,1.621901e+12,2021-05-25 07:56:19,+0800,,@AlbertaAltruist @adolwyn We still pay for it ...,en,[],[],...,,,,,,"[{'screen_name': 'AlbertaAltruist', 'name': 'D...",,,,
14,1396978342000160769,1396978342000160769,1.621901e+12,2021-05-25 07:56:05,+0800,,Tech Update: Billionaire investor Ray Dalio s...,en,"[digitaltransformation, digitalstrategy, digit...",[],...,,,,,,[],,,,
15,1396978321225883649,1396978321225883649,1.621901e+12,2021-05-25 07:56:01,+0800,,Most never self evaluate so no tip no sex hars...,en,[],[],...,,,,,,[],,,,
13,1353491090419167232,1353437312861032449,1.611532e+12,2021-01-25 07:53:17,+0800,,@GuntherSchnabl @franke_media Nein. Nicht der ...,de,[],[],...,,,,,,"[{'screen_name': 'GuntherSchnabl', 'name': 'Gu...",,,,

In [80]:
df2.to_csv("tweets_1_drop_duplicates.csv")

In [79]:
df1.to_csv("tweets_1.csv")